# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseEvents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Networking
  pod 'ReachabilitySwift'
  pod 'Alamofire', '~> 4.7'
  
  
  # Firebase Pods
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  
  
  # Crash and analytics data
  pod 'Crashlytics'
  
  
  # UI
  pod 'SDWebImage', '~> 4.0'
  pod 'NVActivityIndicatorView'

  # Pods for FirebaseEvents

end
